name: Lint

on: [pull_request]

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18.18.2

      - name: Install Dependencies
        run: npm ci

      - name: Run ESLint
        run: npx eslint --ext .js,.jsx,.ts,.tsx .
